language: bash
sudo: required
services:
  - docker
install:
  - sudo apt-get install python3
script:
  - cd tests
  - echo "y" | sudo ./test_enterprise_repo.sh
  - echo "y" | sudo ./test_oss_repo.sh

