language: bash
sudo: required
services:
  - docker
install:
  - sudo apt-get install python3
script:
  - echo $PWD
  - echo "y" | ./tests/test_enterprise_repo.sh
  - echo "y" | ./tests/test_oss_repo.sh

